// Autogenerated with DRAKON Editor 1.25
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Diagnostics;

using Actors;

namespace ActorGui {

public class GuiMachines {
	internal const int Download = 840;
	internal const int Prime = 841;
	internal const int Cancel = 842;

    public partial class MainWindowLogic
        : IActor
    {
        
        // Arguments
        internal IMainWindow Window;
        
        // State
        internal int Worker;
        internal WebClient Web;
        public enum StateNames {
            Deleting,
            Deleted,
            Ready,
            Calculating,
            Downloading
        }
        internal StateNames CurrentState = StateNames.Ready;
        public void OnMessage(IRuntime runtime, int myId, Message message) {
            switch (message.Code) {
                case CallResult.Completed:
                    switch (CurrentState) {
                        case StateNames.Ready:
                            break;
                        case StateNames.Calculating:
                            Calculating_CallResult_Completed(runtime, myId, message);
                            break;
                        case StateNames.Downloading:
                            Downloading_CallResult_Completed(runtime, myId, message);
                            break;
                        default:
                            break;
                    }
                    break;
                case CallResult.Error:
                    switch (CurrentState) {
                        case StateNames.Ready:
                            break;
                        case StateNames.Calculating:
                            Calculating_CallResult_Error(runtime, myId, message);
                            break;
                        case StateNames.Downloading:
                            Downloading_CallResult_Error(runtime, myId, message);
                            break;
                        default:
                            break;
                    }
                    break;
                case Cancel:
                    switch (CurrentState) {
                        case StateNames.Ready:
                            break;
                        case StateNames.Calculating:
                            Calculating_Cancel(runtime, myId, message);
                            break;
                        case StateNames.Downloading:
                            Downloading_Cancel(runtime, myId, message);
                            break;
                        default:
                            break;
                    }
                    break;
                case Download:
                    switch (CurrentState) {
                        case StateNames.Ready:
                            Ready_Download(runtime, myId, message);
                            break;
                        case StateNames.Calculating:
                            break;
                        case StateNames.Downloading:
                            break;
                        default:
                            break;
                    }
                    break;
                case Prime:
                    switch (CurrentState) {
                        case StateNames.Ready:
                            Ready_Prime(runtime, myId, message);
                            break;
                        case StateNames.Calculating:
                            break;
                        case StateNames.Downloading:
                            break;
                        default:
                            break;
                    }
                    break;
                default:
                    break;
            }
        }

        private void Ready_Download(IRuntime runtime, int myId, Message message) {
            // item 88
            string url = (string)message.Payload;
            // item 93
            Debug.WriteLine(url);
            // item 244
            Web = StartDownload(
            	runtime,
            	url,
            	myId
            );
            // item 90
            Window.SwitchToWorking();
            // item 92
            CurrentState = StateNames.Downloading;
        }

        private void Ready_Prime(IRuntime runtime, int myId, Message message) {
            // item 89
            int n = (int)message.Payload;
            // item 94
            Debug.WriteLine(n);
            // item 232
            var calculator = new PrimeCalculator();
            calculator.Client = myId;
            calculator.N = n;
            
            
            Worker = runtime.AddDedicatedActor(
            	calculator
            );
            // item 91
            Window.SwitchToWorking();
            // item 73
            CurrentState = StateNames.Calculating;
        }

        private void Calculating_CallResult_Completed(IRuntime runtime, int myId, Message message) {
            // item 116
            Window.SwitchToReady();
            // item 231
            Window.ReportResult(
            	(string)message.Payload
            );
            // item 82
            CurrentState = StateNames.Ready;
        }

        private void Calculating_CallResult_Error(IRuntime runtime, int myId, Message message) {
            // item 233
            Window.SwitchToReady();
            // item 113
            ReportError(
            	Window,
            	"Calculation failed",
            	message
            );
            // item 82
            CurrentState = StateNames.Ready;
        }

        private void Calculating_Cancel(IRuntime runtime, int myId, Message message) {
            // item 235
            Window.SwitchToReady();
            // item 234
            runtime.RemoveActor(Worker);
            // item 82
            CurrentState = StateNames.Ready;
        }

        private void Calculating_default(IRuntime runtime, int myId, Message message) {
            // item 102
            CurrentState = StateNames.Calculating;
        }

        private void Downloading_CallResult_Completed(IRuntime runtime, int myId, Message message) {
            // item 236
            Window.SwitchToReady();
            // item 246
            byte[] data = (byte[])message.Payload;
            // item 245
            string result = String.Format(
            	"Download completed. Size: {0} bytes.",
            	data.Length
            );
            // item 247
            Window.ReportResult(
            	result
            );
            // item 76
            CurrentState = StateNames.Ready;
        }

        private void Downloading_CallResult_Error(IRuntime runtime, int myId, Message message) {
            // item 119
            Window.SwitchToReady();
            // item 120
            ReportError(
            	Window,
            	"Download failed",
            	message
            );
            // item 76
            CurrentState = StateNames.Ready;
        }

        private void Downloading_Cancel(IRuntime runtime, int myId, Message message) {
            // item 237
            Window.SwitchToReady();
            // item 266
            if (Web == null) {
                // item 76
                CurrentState = StateNames.Ready;
            } else {
                // item 265
                Web.CancelAsync();
                Web = null;
                // item 76
                CurrentState = StateNames.Ready;
            }
        }

        private void Downloading_default(IRuntime runtime, int myId, Message message) {
            // item 111
            CurrentState = StateNames.Downloading;
        }

        public void CleanUp(IRuntime runtime, int myId) {
            if (CurrentState == StateNames.Deleted) {
                return;
            }
            CurrentState = StateNames.Deleted;
            
        }
    }
    public partial class PrimeCalculator
        : IActor
    {
        
        const int ChunkSize = 1000;
        
        // Arguments.
        internal int N;
        internal int Client; // The actor that ordered the computation.
        
        // State
        internal readonly List<int> Primes = new List<int>();
        internal int Current; // The current candidate.
        internal int J;
        public enum StateNames {
            Deleting,
            Deleted,
            EasyChecks,
            Calculation
        }
        internal StateNames CurrentState = StateNames.EasyChecks;
        public void OnMessage(IRuntime runtime, int myId, Message message) {
            switch (message.Code) {
                case Codes.Pulse:
                    switch (CurrentState) {
                        case StateNames.EasyChecks:
                            EasyChecks_Codes_Pulse(runtime, myId, message);
                            break;
                        case StateNames.Calculation:
                            Calculation_Codes_Pulse(runtime, myId, message);
                            break;
                        default:
                            break;
                    }
                    break;
                default:
                    break;
            }
        }

        private void EasyChecks_Codes_Pulse(IRuntime runtime, int myId, Message message) {
            // item 1980001
            if (N == 0) {
                // item 215
                ReportPrimes(
                	runtime,
                	Primes,
                	N,
                	Client
                );
                // item 156
                CurrentState = StateNames.Deleting;
                runtime.RemoveActor(myId);
            } else {
                // item 1980002
                if (N == 1) {
                    // item 211
                    Primes.Add(1);
                    // item 215
                    ReportPrimes(
                    	runtime,
                    	Primes,
                    	N,
                    	Client
                    );
                    // item 156
                    CurrentState = StateNames.Deleting;
                    runtime.RemoveActor(myId);
                } else {
                    // item 1980003
                    if (N == 2) {
                        // item 209
                        Primes.Add(1);
                        Primes.Add(2);
                        // item 215
                        ReportPrimes(
                        	runtime,
                        	Primes,
                        	N,
                        	Client
                        );
                        // item 156
                        CurrentState = StateNames.Deleting;
                        runtime.RemoveActor(myId);
                    } else {
                        // item 1980004
                        if (N < 0) {
                            // item 220
                            runtime.SendMessage(
                            	Client,
                            	CallResult.Error,
                            	new ArgumentException("N", "Negative argument"),
                            	myId
                            );
                            // item 156
                            CurrentState = StateNames.Deleting;
                            runtime.RemoveActor(myId);
                        } else {
                            // item 269
                            Primes.Add(1);
                            Primes.Add(2);
                            Primes.Add(3);
                            // item 216
                            Current = 5;
                            J = 3;
                            // item 214
                            CurrentState = StateNames.Calculation;
                        }
                    }
                }
            }
        }

        private void EasyChecks_default(IRuntime runtime, int myId, Message message) {
            // item 170
            CurrentState = StateNames.EasyChecks;
        }

        private void Calculation_Codes_Pulse(IRuntime runtime, int myId, Message message) {
            // item 1790001
            int i = 0;
            while (true) {
                // item 1790002
                if (i < ChunkSize) {
                    
                } else {
                    // item 159
                    CurrentState = StateNames.Calculation;
                    break;
                }
                // item 193
                if (Current > N) {
                    // item 270
                    // item 230
                    ReportPrimes(
                    	runtime,
                    	Primes,
                    	N,
                    	Client
                    );
                    // item 195
                    CurrentState = StateNames.Deleting;
                    runtime.RemoveActor(myId);
                    break;
                } else {
                    
                }
                // item 181
                if (J * J > Current) {
                    // item 191
                    // item 192
                    Primes.Add(Current);
                    // item 190
                    J = 3;
                    Current += 2;
                } else {
                    // item 185
                    if (Current % J == 0) {
                        // item 190
                        J = 3;
                        Current += 2;
                    } else {
                        // item 184
                        J += 2;
                    }
                }
                // item 1790003
                i++;
            }
        }

        private void Calculation_default(IRuntime runtime, int myId, Message message) {
            // item 178
            CurrentState = StateNames.Calculation;
        }

        public void CleanUp(IRuntime runtime, int myId) {
            if (CurrentState == StateNames.Deleted) {
                return;
            }
            CurrentState = StateNames.Deleted;
            
        }
    }

    private static void DownloadCompleted(IRuntime runtime, int caller, DownloadDataCompletedEventArgs e) {
        // item 255
        if (e.Cancelled) {
            // item 258
            runtime.SendMessage(
            	caller,
            	Cancel,
            	null,
            	0
            );
        } else {
            // item 259
            if (e.Error == null) {
                // item 262
                runtime.SendMessage(
                	caller,
                	CallResult.Completed,
                	e.Result,
                	0
                );
            } else {
                // item 261
                runtime.SendMessage(
                	caller,
                	CallResult.Error,
                	e.Error,
                	0
                );
            }
        }
    }

    private static void ReportError(IMainWindow Window, string start, Message message) {
        // item 126
        string text;
        Exception ex = message.Payload as Exception;
        // item 128
        if (ex == null) {
            // item 131
            text = start;
        } else {
            // item 127
            text = start + "\n" + ex.Message;
        }
        // item 132
        Window.ReportError(text);
    }

    private static void ReportPrimes(IRuntime runtime, List<int> primes, int n, int client) {
        // item 229
        string[] primesAsText = primes
        	.Select(p => p.ToString())
        	.ToArray();
        // item 226
        string primeString = String.Join(
        	"\n",
        	primesAsText
        );
        // item 227
        string result = String.Format(
        	"Prime numbers up to {0}: {1} found:\n{2}",
        	n,
        	primes.Count,
        	primeString
        );
        // item 228
        runtime.SendMessage(
        	client,
        	CallResult.Completed,
        	result,
        	0
        );
    }

    private static WebClient StartDownload(IRuntime runtime, string url, int receiverId) {
        // item 263
        WebClient web = new WebClient();
        web.DownloadDataCompleted += (sender, e) =>
        {
        	DownloadCompleted(runtime, receiverId, e);
        };
        // item 264
        try {
        	web.DownloadDataAsync(new Uri(url));
        } catch (Exception ex) {
        	runtime.SendMessage(
        		receiverId,
        		CallResult.Error,
        		ex,
        		0
        	);
        }
        // item 249
        return web;
    }
}
}
